import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { useEffect, useState } from 'react'
import io from 'socket.io-client'
let socket;

const Home = () => {
  const [input, setInput] = useState('')
  const [counter, setCounter] = useState('')

  useEffect(() => { socketInitializer() }, [])

  const socketInitializer = async () => {
    await fetch('/api/socket');
    socket = io()

    socket.on('connect', () => {
      console.log('connected')
    })

    socket.on('counter', msg => {
      setCounter(msg)
    })
  }

  const onChangeHandler = (e) => {
    setInput(e.target.value)
  }

  const onStartController = (e) => {
    socket.emit('start', input)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Counter Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {counter}
        </h1>
        <input
          placeholder="Set Counter"
          type="number"
          value={input}
          onChange={onChangeHandler}
        />
        <button type="button" onClick={onStartController}>Start</button>
      </main>
    </div>
  )
}

export default Home;